<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFJbrVLX\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFJbrVLX/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFJbrVLX.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFJbrVLX\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerFJbrVLX\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'FJbrVLX',
    'container.build_id' => 'ddaecf0b',
    'container.build_time' => 1518267381,
));
